### PR TITLE
Removes ConfidentialityLevel enumeration and changes mappings

### PR DESCRIPTION
**Pull request by cmgrote**
... to a simple integer (relying on naming convention of terms).

Corresponding change in the sample data is https://github.com/odpi/egeria/pull/1113

### CODE REVIEW

**Comment by danielaotelea** [comment]
Hello Criss,

I have tested the new version of IGC Proxy and I'm getting the following exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[na:1.8.0_201]
	at org.odpi.egeria.connectors.ibm.igc.repositoryconnector.mapping.classifications.ConfidentialityMapper.addMappedOMRSClassifications(ConfidentialityMapper.java:102) ~[egeria-connector-ibm-igc-package-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.egeria.connectors.ibm.igc.repositoryconnector.mapping.entities.EntityMapping.setupEntityObj(EntityMapping.java:511) ~[egeria-connector-ibm-igc-package-1.1-SNAPSHOT.jar!/:na]

**Comment by cmgrote** [comment]
@danielaotelea have you also loaded the new sample data linked via the other PR?  (Or manually changed the names of the IGC terms to the following:

- `Unclassified` --> `0 - Unclassified`
- `Internal` --> `1 - Internal`
- `Confidential` --> `2 - Confidential`
- `Sensitive` --> `3 - Sensitive`
- `Restricted` --> `4 - Restricted`
- `Other` --> `99 - Other`

I'll add in better error handling in the meantime, but the names will need to change as per above for the new code to work...

**Comment by danielaotelea** [comment]
I have changed the IGC terms. It is working now. Thanks!

**Comment by cmgrote** [comment]
Excellent, thanks for confirming!  I'll merge the respective PRs 😄

**Pull request merged**
