### PR TITLE
Initial migration from Egeria core

### PR DESCRIPTION
**Pull request by cmgrote**
Initial migration of connector code from Egeria core

### CODE REVIEW

**Comment by cmgrote** [comment]
@jmertic can we setup the same controls we have on Egeria core on this repository as well?

Things like:
- automated Jenkins build
- review as optional

Thanks!

**Comment by jmertic** [comment]
@cmgrote Added the DCO check

@schannamallu Can you help with getting this integrated into the Jenkins build?

**Comment by schannamallu** [comment]
@jmertic, I will integrate them. Will update once done.

**Comment by schannamallu** [comment]
Recheck

**Comment by schannamallu** [comment]
Recheck

**Comment by schannamallu** [comment]
Recheck

**Comment by schannamallu** [comment]
Recheck

**Comment by planetf1** [comment]
FYI for future changes to build infrastructure we should use the odpi/ci-management project
Note - we'll need the igc docker image created somewhere, so this project may also need that element added to, which can then be consumed by our helm charts

**Comment by cmgrote** [comment]
> Note - we'll need the igc docker image created somewhere, so this project may also need that element added to, which can then be consumed by our helm charts

The IGC docker image cannot be created through ODPi build infrastructure — it requires commercially licensed software and entitlements.  We could move the helm template for it here, but the image itself would always need to remain external.

**Comment by planetf1** [comment]
I wasn't thinking about IGC itself (which is all commercial) but the proxy we use as part of the VDC chart, ie server chassis with the igc connector/event mapper loaded pointed to a remote repo.

The VDC chart will be dependent on that image - albeit only when IGC is being used. 

If we think that includes proprietary code too, then that can't be built here, but I had thought the proxy would be open source only? Also if it is proprietary it would be great if we could persuade the proprotery owners to support the required images....

**Comment by cmgrote** [comment]
Gotcha -- indeed the proxy will be fine: but my intention would be to just re-use the Egeria core (OMAG Server Platform) image and inject the connector at startup; rather than needing to maintain different images for every potential combination of connectors...  I've added an issue to the other repo (for now) to track that migration: all dependent on us agreeing the `ZIP` vs `JAR` approach first, though, so probably worth discussing on the Tuesday call 😄

**Comment by schannamallu** [comment]
@cmgrote, @jmertic - Integrated with the jenkins builds. Can you check and confirm.

**Comment by cmgrote** [comment]
Thanks @schannamallu !  I saw it working on an earlier PR 👍

**Pull request merged**
